export const FORM_STATE = {
  userVet: null,
  age: '',
  name: '',
  city: '',
  color: '',
  gender: '',
  weight: '',
  images: [],
  country: '',
  category: '',
  newImages: [],
  adopted: false,
  textAddress: '',
  description: '',
  userAdopted: null,
  medicalNotes: [],
  titleMedicalNote: '',
  detailMedicalNote: '',
  location: {
    lat: 0,
    lng: 0,
  },
};
